### ISSUE TITLE
Ordnernamen: keine Abkürzungen verwenden

### ISSUE THREAD

**Issue by nullmightybofo** [Painkilla/VU-351.019-Elektrodynamik#2]
Vorschlag: Verwende keine Abkürzungen bei den Ordnernamen in src/ sondern vollständige Wörter damit Bedeutung klarer ist.

**Comment by Painkilla** [comment]
Die Abkürzungen sind aus dem Unix/Linux Umfeld um Tipparbeit in der Konsole und beim händisch kompilieren zu ersparen. Umlaute und Großbuchstaben sind auch bewusst weggelassen um Komplikationen zu vermeiden.
Wie würdest du die Ordner benennen?

**Comment by Painkilla** [comment]
Ich schließe mal das issue. Strukturelle Verbesserungen sind jetzt im conf-repo
